### ISSUE TITLE
lots of crashes being reported by users playing music

### ISSUE THREAD

**Issue by cpg** [amahi/android#198]
W're getting lots of crashes in ServerFile.getMime calls. To reproduce, click on a music file to play! Play starts, but it crashes quickly and system asks the user to report a crash report. Music continues playing, however.

This appears to occur only on local share files. It appears to work from the `Welcome to Amahi` demo cloud server.

we're getting lots of crash reports that look like this. Any idea what could be causing this? and what should be a reliable fix?

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.amahi.anywhere.server.model.ServerFile.getMime()' on a null object reference
       at org.amahi.anywhere.util.Intents$Builder.getServerFileActivity(Intents.java:99)
       at org.amahi.anywhere.util.Intents$Builder.buildServerFileIntent(Intents.java:121)
       at org.amahi.anywhere.service.AudioService.setUpAudioPlayerNotification(AudioService.java:289)
       at org.amahi.anywhere.service.AudioService.playAudio(AudioService.java:389)
       at org.amahi.anywhere.service.AudioService.handleAudioFocusGain(AudioService.java:477)
       at org.amahi.anywhere.service.AudioService.onAudioFocusChange(AudioService.java:455)
       at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:3119)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
```

**Comment by cpg** [comment]
We're getting a lot of these failures.

On user indicated the following:

```
the app was idle, it seems to crash after phone calls I noticed and have not noticed a pattern on other times
```

**Comment by cpg** [comment]
More details:

> Started a mp3 and it crashed, but music continues to play until I hit "report" or OK

device model: LG VS986

**Comment by cpg** [comment]
Update, update, it's got to do with the format of the song. I uploaded one called `Williams - Star Wars` to the demo server (under Demo > music) where this crash is reproducible for me.

**Comment by joydeepsaha05** [comment]
I could reproduce the crash from the demo server. Seems to be an issue with the status bar's notification text being assigned a null value.

**Comment by octacode** [comment]
@cpg Yes! even I was able to replicate the same! Every time I make a call I get the message saying that 
`Amahi has stopped`. Looking into the reason for the crash.
