### ISSUE TITLE
crash in client.ServerClient.getFileUri()

### ISSUE THREAD

**Issue by cpg** [amahi/android#207]
this is our top crash at the moment:

```
Fatal Exception: java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:471)
       at android.net.Uri$StringUri.<init>(Uri.java:461)
       at android.net.Uri.parse(Uri.java:433)
       at org.amahi.anywhere.server.client.ServerClient.getFileUri(ServerClient.java:218)
       at org.amahi.anywhere.service.VideoService.getVideoUri(VideoService.java:98)
       at org.amahi.anywhere.service.VideoService.setUpVideoPlayback(VideoService.java:91)
       at org.amahi.anywhere.service.VideoService.startVideo(VideoService.java:87)
       at org.amahi.anywhere.activity.ServerFileVideoActivity.setUpVideoPlayback(ServerFileVideoActivity.java:232)
       at org.amahi.anywhere.activity.ServerFileVideoActivity.onServiceConnected(ServerFileVideoActivity.java:173)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1320)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1337)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
...
```

**Comment by octacode** [comment]
I'd like to take up the issue.

**Comment by cpg** [comment]
We don't know. It has to be solved by logical deduction.
