### ISSUE TITLE
crash in getPreviousAudioFile()

### ISSUE THREAD

**Issue by cpg** [amahi/android#209]
the app's next top crash is this:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.indexOf(java.lang.Object)' on a null object reference
       at org.amahi.anywhere.service.AudioService.getPreviousAudioFile(AudioService.java:379)
       at org.amahi.anywhere.service.AudioService.startPreviousAudio(AudioService.java:370)
       at org.amahi.anywhere.service.AudioService.access$200(AudioService.java:78)
       at org.amahi.anywhere.service.AudioService$MediaSessionCallback.onSkipToPrevious(AudioService.java:526)
       at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onSkipToPrevious(MediaSessionCompat.java:1008)
       at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onSkipToPrevious(MediaSessionCompatApi21.java:205)
       at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:836)
       at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onMediaButtonEvent(MediaSessionCompatApi21.java:170)
       at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
...
```

**Comment by cpg** [comment]
BTW, we have a similar number of crashes with getNextAudioFile(). Maybe it's the same bug or a symmetrical one.
