### ISSUE TITLE
Beta branch app crashes when user click on item on share screen

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#297]
App crashes with logs below

```
E/AndroidRuntime: FATAL EXCEPTION: main
 Process: org.amahi.anywhere, PID: 7101
 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.amahi.anywhere/org.amahi.anywhere.activity.ServerFilesActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class fragment
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2555)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629)
     at android.app.ActivityThread.access$800(ActivityThread.java:182)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
     at android.os.Handler.dispatchMessage(Handler.java:111)
     at android.os.Looper.loop(Looper.java:194)
     at android.app.ActivityThread.main(ActivityThread.java:5706)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
  Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class fragment
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
     at org.amahi.anywhere.activity.ServerFilesActivity.onCreate(ServerFilesActivity.java:100)
     at android.app.Activity.performCreate(Activity.java:6092)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629) 
     at android.app.ActivityThread.access$800(ActivityThread.java:182) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
     at android.os.Handler.dispatchMessage(Handler.java:111) 
     at android.os.Looper.loop(Looper.java:194) 
     at android.app.ActivityThread.main(ActivityThread.java:5706) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
  Caused by: java.lang.IllegalArgumentException: Invalid application ID: null
     at com.google.android.gms.cast.CastMediaControlIntent.zza(Unknown Source)
     at com.google.android.gms.cast.CastMediaControlIntent.categoryForCast(Unknown Source)
     at com.google.android.gms.internal.zzaxk.<init>(Unknown Source)
     at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
     at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
     at com.google.android.gms.cast.framework.media.uicontroller.UIMediaController.<init>(Unknown Source)
     at com.google.android.gms.cast.framework.media.widget.MiniControllerFragment.onCreateView(Unknown Source)
     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1296)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1513)
     at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1727)
     at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3517)
     at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
     at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
     at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
     at org.amahi.anywhere.activity.ServerFilesActivity.onCreate(ServerFilesActivity.java:100) 
     at android.app.Activity.performCreate(Activity.java:6092) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629) 
     at android.app.ActivityThread.access$800(ActivityThread.java:182) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
     at android.os.Handler.dispatchMessage(Handler.java:111) 
     at android.os.Looper.loop(Looper.java:194) 
     at android.app.ActivityThread.main(ActivityThread.java:5706) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12980721/36849515-4514a31c-1d8a-11e8-919d-0157444cdd4c.gif)

**Comment by csoni111** [comment]
It seems you have cast enabled, and since you do not have a chromecast app id in api.properties file, the app is crashing.
@cpg we must supply the `chromecast.app.id` too in `api.properties` file.

**Comment by mohitsvnit** [comment]
yes. After adding `chromecast.app.id` in `api.properties`, it's not crashing now.
