### ISSUE TITLE
Fatal exception. Bad notification for startForeground.

### ISSUE THREAD

**Issue by shivammaindola** [amahi/android#443]
This exception occurs in SDK 27 (Android 8.1) but not in lower SDK versions.
```
Fatal Exception: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 groupKey=com.clamber vis=PRIVATE)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
Here is the Gif of the error.

![video2gif_20190319_202410](https://user-images.githubusercontent.com/39567362/54617310-05cef380-4a87-11e9-9a52-40112f1e6684.gif)

**Comment by csoni111** [comment]
Resolved in #444
