### ISSUE TITLE
Beta crashes with fastscroll

### ISSUE THREAD

**Issue by cpg** [amahi/android#672]
**Describe the issue**
When browsing a specific share called Movies that has 126 files in it, the app (built from `beta` as of this writing) crashes. It does not crash with other shares, which 
```
2020-09-11 02:25:06.503 13786-13786/? E/.amahi.anywher: Unknown bits set in runtime_flags: 0x8000
2020-09-11 02:25:37.637 13786-13786/org.amahi.anywhere E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.amahi.anywhere, PID: 13786
    java.lang.ClassCastException: androidx.recyclerview.widget.RecyclerView cannot be cast to com.l4digital.fastscroll.FastScrollView
        at org.amahi.anywhere.fragment.ServerFilesFragment.getFastScrollView(ServerFilesFragment.java:237)
        at org.amahi.anywhere.fragment.ServerFilesFragment.setUpRecyclerLayout(ServerFilesFragment.java:509)
        at org.amahi.anywhere.fragment.ServerFilesFragment.setUpFilesAdapter(ServerFilesFragment.java:493)
        at org.amahi.anywhere.fragment.ServerFilesFragment.setUpFiles(ServerFilesFragment.java:209)
        at org.amahi.anywhere.fragment.ServerFilesFragment.onActivityCreated(ServerFilesFragment.java:169)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**To Reproduce or Feature details**
0. Log in
1. Go to a share that has a number of files in it
2. It ought to crash

**Expected behavior**
Not crash

**Smartphone (please complete as much of the following information as possible):**
 - Device: Pixel sim
 - OS: Android 10
 - Version: build from `beta` at 0f7c1483e336294d93978e947426f5935fd1401f

**Additional context**

To debug a little, I went to the folder of the `Pictures` share, which was empty, and I created symlinks to every file in the `Movies` folder. So they are now similar in number of files. The app does *not* crash on the `Pictures` share.

I further went to look for any dot files in `Movies` or something and there was one, deleted it and the same still happened. Not sure why this could be happening.

**Comment by devptyagi** [comment]
Can I work on this issue?
