### ISSUE TITLE
App Crashes When Video Player is Closed

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [amahi/android#746]
**Describe the issue**
When we open any video in the app and close it after it starts, then the app crashes. Crash report:-
```
02-25 17:21:00.951 3196-3302/org.amahi.anywhere E/AndroidRuntime: FATAL EXCEPTION: Thread-237
    Process: org.amahi.anywhere, PID: 3196
    java.lang.IllegalStateException: can't get VLCObject instance
        at org.videolan.libvlc.MediaPlayer.nativeStop(Native Method)
        at org.videolan.libvlc.MediaPlayer.access$700(MediaPlayer.java:45)
        at org.videolan.libvlc.MediaPlayer$4.run(MediaPlayer.java:627)
        at java.lang.Thread.run(Thread.java:818)
```

**To Reproduce or Feature details**
1. Go to Videos
2. Click on any video
3. Let it play and then press the back button
4. See that the app crashes.

**Current behavior**

https://user-images.githubusercontent.com/17739006/109152226-351d2d80-7791-11eb-8dd5-8763c6e1420c.mp4

**Smartphone (please complete as much of the following information as possible):**
 - All supported android devices (I tested it on API 21, 25, 29, and 30)

**Additional context**
Maybe the error is caused by a bug in the VLC library

**Comment by kartikeysaran** [comment]
Can i work on this issue ?

**Comment by kartikeysaran** [comment]
@Prakhar-Agarwal-byte why does the app shows "Connection error ! Check your settings and try again " even after successful registration

**Comment by Prakhar-Agarwal-byte** [comment]
@kartikeysaran You have to first get API keys. You can find the instructions on how to get it in Readme file.

**Comment by kartikeysaran** [comment]
> @kartikeysaran You have to first get API keys. You can find the instructions on how to get it in Readme file.

Thanks !

**Comment by kartikeysaran** [comment]
Hey prakhar i have mailed regarding the Access to API keys ! till when will i get a reply . Thankyou !!

**Comment by Prakhar-Agarwal-byte** [comment]
> Hey prakhar i have mailed regarding the Access to API keys ! till when will i get a reply . Thankyou !!

You will get them soon.
